[package]
name = "qalam-lib"
version = "0.1.0"
authors = ["Eli Heuer <elih@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
norad = { version = "0.3.1", features = ["druid", "rayon"] }
